### ISSUE TITLE
TinyMCE wird auch bei eigenem HTML-Code angezeigt

### ISSUE THREAD

**Issue by MacKP** [Toflar/contao-tinymce4-abbr-plugin#1]
Um das richtig in der dcaconfig anzupassen reicht es das die if-Schleife so zu schreiben:

```
if (isset($fieldConfig['eval']['rte']) && substr($fieldConfig['eval']['rte'], 0, 3) !== 'ace') {
```

Danke @discordier

**Comment by Toflar** [comment]
Das hängt von etlichen Faktoren ab, aber ja - das ist eine Möglichkeit. Was soll ich mit dem Ticket jetzt tun? :D

**Comment by MacKP** [comment]
Ja, das dachte ich mir schon. Nur dein Beispielcode sorgt halt dafür, das man beim eigenen HTML Code eben auf einmal auch den Tiny hat, was die Geschichte etwas unschön macht ;-)
Eventuell kannst du das ja anpassen?

**Comment by Toflar** [comment]
Und was hat das mit dem ACE zu tun? :D

**Comment by MacKP** [comment]
Ich bekomme mit dem Code den ich gepostet habe wieder den ACE angezeigt anstelle des TinyMCE für das Modul 'Eigener HTML-Code'.
Ansonsten bekomme ich bei Longtext-Feldern (also da wo der TinyMCE angezeigt werden soll) auch die Konfig geladen mit dem abbr drinn.
Ich frage mich gerade ob wir uns irgendwie nicht verstehen xD

**Comment by discordier** [comment]
@Toflar Du killst jeglichen `rte` eval weg. Ich habe es beschraenkt, dass zumindest mal alle `ace*` bestehen bleiben.
Das kann man logischerweise auch noch weiter treiben und ggf. nur `tinyMCE` oder sowas ersetzen, aber nunja, du wirst schon wissen was in deiner Erweiterung das richtige ist.

**Comment by Toflar** [comment]
> nunja, du wirst schon wissen was in deiner Erweiterung das richtige ist.

Nö, jeder muss das selber wissen. Man muss halt das DCA verstehen^^

**Comment by MacKP** [comment]
Hm das ist schon klar, das man es verstehen sollte. Wäre trotzdem nett, wenn du da ein Beispiel bringen würdest, was nicht dafür sorgt, das man dann mehr Probleme als nutzen hat.

**Comment by Toflar** [comment]
Ich weiss ehrlich gesagt nicht, wie ich das tun soll. Es gibt haufenweise Möglichkeiten die Config zu ändern und das kann ich selber auch nicht ändern.
